### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by rgwch** [sajov/feathers-solr#6]
The "Getting Started" Example in the readme file doesn't work ("SolrClient is not a function").

**Comment by rgwch** [comment]
See my [Pull request](https://github.com/sajov/feathers-solr/pull/8)

**Comment by sajov** [comment]
See working [example](https://github.com/sajov/feathers-solr/blob/master/example/index.js#L58)
Model option expect a `SolrClient` instance
`
const options = {
  Model: SolrClient(fetch, solrServer),
  paginate: {},
  events: ['testing'],
  multi: true
};
app.use('gettingstarted', new Service(options));
`

**Comment by rgwch** [comment]
Thanks for quick help! This example worked.

**Comment by sajov** [comment]
Thank you!
