### ISSUE TITLE
Remove does not work correctly

### ISSUE THREAD

**Issue by rgwch** [sajov/feathers-solr#7]
service.remove(null,{query: { foo: "bar"}}) throws an error. Service.remove(null, {foo:"bar"}) works, but if I understand the feathers docs correctly, the first should be correct.

**Comment by sajov** [comment]
yes thats right, will fix it soon. thank you!

**Comment by sajov** [comment]
`service.remove(null,{query: { foo: "bar"}}) `  should work.
Does [options](https://docs.feathersjs.com/api/databases/common.html#service-options) contain `multi: true`? 
See working [example](https://github.com/sajov/feathers-solr/blob/master/example/index.js#L58)
Run example with `bin/solr start -e schemaless`
